import type { Meta, StoryObj } from '@storybook/react';
import { Textarea } from '../components/Textarea';

const meta = {
  title: 'Components/Textarea',
  component: Textarea,
  tags: ['autodocs'],
  argTypes: {
    label:       { control: 'text',    description: 'Label above the textarea' },
    hint:        { control: 'text',    description: 'Helper text shown below' },
    error:       { control: 'text',    description: 'Validation error — replaces hint when set' },
    placeholder: { control: 'text',   description: 'Placeholder text' },
    rows:        { control: { type: 'number', min: 1, max: 20 }, description: 'Visible row count' },
    resize:      { control: 'select', options: ['none', 'vertical', 'horizontal', 'both'], description: 'CSS resize behaviour' },
    disabled:    { control: 'boolean' },
  },
} satisfies Meta<typeof Textarea>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  args: {
    label:       'Workflow Description',
    placeholder: 'Describe what this workflow does…',
    hint:        'Used in reports and run logs.',
    rows:        4,
    resize:      'vertical',
    disabled:    false,
  },
};

export const Default: Story = {
  args: {
    label:       'Workflow Description',
    placeholder: 'Describe what this workflow does…',
    hint:        'Used in reports and run logs.',
  },
};

export const AIPrompt: Story = {
  args: {
    label:       'Prompt',
    placeholder: 'Describe your workflow in plain language…',
    defaultValue:'When a new hire joins, send welcome email, provision tools, and schedule 1:1s',
    rows:        3,
    resize:      'none',
    hint:        'AI will convert this into workflow steps.',
  },
};

export const WithError: Story = {
  args: {
    label:       'Trigger Condition',
    placeholder: 'Describe when this workflow should start…',
    error:       'Trigger condition is required before deploying.',
  },
};

export const Disabled: Story = {
  args: {
    label:        'System Notes',
    defaultValue: 'Auto-generated by the AI builder on Apr 21, 2026.',
    disabled:     true,
    hint:         'Managed automatically — cannot be edited.',
  },
};

export const NoResize: Story = {
  args: {
    label:       'Webhook Payload',
    rows:        6,
    resize:      'none',
    placeholder: 'Paste your JSON payload…',
    className:   'font-mono text-xs',
  },
};

export const NoLabel: Story = {
  args: {
    placeholder: 'Add a comment…',
    rows:        3,
  },
};
